### ISSUE TITLE
Cannot save.

### ISSUE THREAD

**Issue by Jesus10101** [KIRAcc/mhst#1]
あなたはそれを編集した後、ファイルを保存することはできません。

**Comment by KIRAcc** [comment]
I confirmed the issue at 2ch(Japanese BBS) and resolved it on [the commit named "The small bug fixed"](https://github.com/KIRAcc/mhst/commit/cfaf95f19ce6a5ec59fda8149255b89ed6f04d28).
If you still can't save now, please comment again.
